# Generated by Django 2.0.2 on 2019-09-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20190920_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('zj', '中级'), ('cj', '初级'), ('gj', '高级')], max_length=2, verbose_name='难度'),
        ),
    ]
