# Generated by Django 2.0.2 on 2019-09-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20190921_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('gj', '高级'), ('cj', '初级'), ('zj', '中级')], max_length=2, verbose_name='难度'),
        ),
    ]
