# Generated by Django 2.0.2 on 2019-09-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20190923_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('zj', '中级'), ('gj', '高级'), ('cj', '初级')], max_length=2, verbose_name='难度'),
        ),
    ]
