# Generated by Django 2.0.2 on 2019-09-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20190920_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (3, '讲师'), (2, '课程机构')], default=1, verbose_name='收藏类型'),
        ),
    ]
